-- ============================================================================
-- 표준 와이드 무대 — 15테마 일괄 시드 (반가 제외 · PLAN-theme-stage-common-v2 §2)
--
-- 테마마다 바뀌는 것은 **장소**(벽·바닥 뮤럴 2장 + 조명색)뿐이고, 단상·제단 상판 같은
-- **살림**은 반가 스프라이트를 그대로 공용한다. 좌표를 테마마다 다시 정하지 않는다 —
-- 정하는 순간 가족 선반장·의식각·앵커·테스트가 테마 수만큼 갈라진다.
--
-- ⚠️ 이 파일은 **생성물**이다. 손으로 고치지 말 것:
--      node scripts/shrine-assets/build-theme-stage-seed.mjs
--    기하 정본  lib/domain/shrine/theme-stage-geometry.json
--    도메인     lib/domain/shrine/theme-stage.ts (buildThemeStage)
--    대조 게이트 lib/domain/shrine/__tests__/theme-stage.test.ts — 파일 ≠ 재생성이면 실패한다
--
-- ⚠️ 적용 전제 — 테마마다 뮤럴 2장이 public/ 에 있어야 한다:
--      public/shrine/stage/<code>/room-wall-mural.webp
--      public/shrine/stage/<code>/room-floor-mural.webp
--    없으면 404 를 StageLayers onError 가 **조용히 숨겨** 어두운 빈 방이 된다(예외도 로그도 없다).
--    그래서 배포 순서는 «코드 → 뮤럴 → 이 시드» 다.
--
-- ⚠️ 시안 1테마만 먼저 켜려면 그 테마의 update 한 문장만 실행한다(종각 등).
--    재실행은 무해하다 — 이미 zones 를 든 행은 where 조건에서 걸러진다(반가도 같은 이유로 안전).
--
-- 원복 — 테마 하나를 단일 무대(레거시 room.webp)로 되돌리기:
--   update public.shrine_theme_packs set stage = null where code = '<code>';
-- 원복 — 두루마리만 걷고 단일 무대 세트는 남기기(폭 100 항등 폴백):
--   update public.shrine_theme_packs set stage = stage - 'zones' - 'width' where code = '<code>';
-- ============================================================================

-- choga (무속성 · #C9A84C)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/choga/room-wall-mural.webp","flooringUrl":"/shrine/stage/choga/room-floor-mural.webp","structures":[{"code":"platform-choga","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-choga","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#C9A84C","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/choga/room-wall-mural.webp","flooringUrl":"/shrine/stage/choga/room-floor-mural.webp","structures":[{"code":"platform-choga","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-choga","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'choga' and (stage -> 'zones') is null;

-- yonggung (water · #2d5f8a)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/yonggung/room-wall-mural.webp","flooringUrl":"/shrine/stage/yonggung/room-floor-mural.webp","structures":[{"code":"platform-yonggung","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-yonggung","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#2d5f8a","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/yonggung/room-wall-mural.webp","flooringUrl":"/shrine/stage/yonggung/room-floor-mural.webp","structures":[{"code":"platform-yonggung","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-yonggung","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'yonggung' and (stage -> 'zones') is null;

-- dokkaebi (fire · #9e2b2b)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/dokkaebi/room-wall-mural.webp","flooringUrl":"/shrine/stage/dokkaebi/room-floor-mural.webp","structures":[{"code":"platform-dokkaebi","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-dokkaebi","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#9e2b2b","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/dokkaebi/room-wall-mural.webp","flooringUrl":"/shrine/stage/dokkaebi/room-floor-mural.webp","structures":[{"code":"platform-dokkaebi","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-dokkaebi","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'dokkaebi' and (stage -> 'zones') is null;

-- seolbit (metal · #c9a84c)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/seolbit/room-wall-mural.webp","flooringUrl":"/shrine/stage/seolbit/room-floor-mural.webp","structures":[{"code":"platform-seolbit","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-seolbit","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#c9a84c","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/seolbit/room-wall-mural.webp","flooringUrl":"/shrine/stage/seolbit/room-floor-mural.webp","structures":[{"code":"platform-seolbit","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-seolbit","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'seolbit' and (stage -> 'zones') is null;

-- daljip (earth · #d4a017)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/daljip/room-wall-mural.webp","flooringUrl":"/shrine/stage/daljip/room-floor-mural.webp","structures":[{"code":"platform-daljip","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-daljip","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#d4a017","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/daljip/room-wall-mural.webp","flooringUrl":"/shrine/stage/daljip/room-floor-mural.webp","structures":[{"code":"platform-daljip","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-daljip","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'daljip' and (stage -> 'zones') is null;

-- hongsal (fire · #9e2b2b)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/hongsal/room-wall-mural.webp","flooringUrl":"/shrine/stage/hongsal/room-floor-mural.webp","structures":[{"code":"platform-hongsal","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-hongsal","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#9e2b2b","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/hongsal/room-wall-mural.webp","flooringUrl":"/shrine/stage/hongsal/room-floor-mural.webp","structures":[{"code":"platform-hongsal","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-hongsal","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'hongsal' and (stage -> 'zones') is null;

-- byeolbat (무속성 · #C9A84C)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/byeolbat/room-wall-mural.webp","flooringUrl":"/shrine/stage/byeolbat/room-floor-mural.webp","structures":[{"code":"platform-byeolbat","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-byeolbat","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#C9A84C","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/byeolbat/room-wall-mural.webp","flooringUrl":"/shrine/stage/byeolbat/room-floor-mural.webp","structures":[{"code":"platform-byeolbat","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-byeolbat","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'byeolbat' and (stage -> 'zones') is null;

-- dangsan (wood · #4a7c59)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/dangsan/room-wall-mural.webp","flooringUrl":"/shrine/stage/dangsan/room-floor-mural.webp","structures":[{"code":"platform-dangsan","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-dangsan","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#4a7c59","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/dangsan/room-wall-mural.webp","flooringUrl":"/shrine/stage/dangsan/room-floor-mural.webp","structures":[{"code":"platform-dangsan","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-dangsan","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'dangsan' and (stage -> 'zones') is null;

-- yeondeung (fire · #9e2b2b)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/yeondeung/room-wall-mural.webp","flooringUrl":"/shrine/stage/yeondeung/room-floor-mural.webp","structures":[{"code":"platform-yeondeung","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-yeondeung","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#9e2b2b","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/yeondeung/room-wall-mural.webp","flooringUrl":"/shrine/stage/yeondeung/room-floor-mural.webp","structures":[{"code":"platform-yeondeung","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-yeondeung","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'yeondeung' and (stage -> 'zones') is null;

-- seonang (earth · #d4a017)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/seonang/room-wall-mural.webp","flooringUrl":"/shrine/stage/seonang/room-floor-mural.webp","structures":[{"code":"platform-seonang","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-seonang","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#d4a017","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/seonang/room-wall-mural.webp","flooringUrl":"/shrine/stage/seonang/room-floor-mural.webp","structures":[{"code":"platform-seonang","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-seonang","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'seonang' and (stage -> 'zones') is null;

-- jangdok (earth · #d4a017)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/jangdok/room-wall-mural.webp","flooringUrl":"/shrine/stage/jangdok/room-floor-mural.webp","structures":[{"code":"platform-jangdok","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-jangdok","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#d4a017","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/jangdok/room-wall-mural.webp","flooringUrl":"/shrine/stage/jangdok/room-floor-mural.webp","structures":[{"code":"platform-jangdok","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-jangdok","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'jangdok' and (stage -> 'zones') is null;

-- daejanggan (metal · #c9a84c)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/daejanggan/room-wall-mural.webp","flooringUrl":"/shrine/stage/daejanggan/room-floor-mural.webp","structures":[{"code":"platform-daejanggan","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-daejanggan","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#c9a84c","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/daejanggan/room-wall-mural.webp","flooringUrl":"/shrine/stage/daejanggan/room-floor-mural.webp","structures":[{"code":"platform-daejanggan","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-daejanggan","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'daejanggan' and (stage -> 'zones') is null;

-- jonggak (metal · #c9a84c)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/jonggak/room-wall-mural.webp","flooringUrl":"/shrine/stage/jonggak/room-floor-mural.webp","structures":[{"code":"platform-jonggak","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-jonggak","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#c9a84c","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/jonggak/room-wall-mural.webp","flooringUrl":"/shrine/stage/jonggak/room-floor-mural.webp","structures":[{"code":"platform-jonggak","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-jonggak","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'jonggak' and (stage -> 'zones') is null;

-- saemgut (water · #2d5f8a)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/saemgut/room-wall-mural.webp","flooringUrl":"/shrine/stage/saemgut/room-floor-mural.webp","structures":[{"code":"platform-saemgut","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-saemgut","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#2d5f8a","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/saemgut/room-wall-mural.webp","flooringUrl":"/shrine/stage/saemgut/room-floor-mural.webp","structures":[{"code":"platform-saemgut","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-saemgut","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'saemgut' and (stage -> 'zones') is null;

-- naru (water · #2d5f8a)
update public.shrine_theme_packs set stage = '{"wallpaperUrl":"/shrine/stage/naru/room-wall-mural.webp","flooringUrl":"/shrine/stage/naru/room-floor-mural.webp","structures":[{"code":"platform-naru","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-naru","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}],"light":{"color":"#2d5f8a","intensity":0.5,"origin":{"x":50,"y":52}},"width":320,"zones":[{"code":"daecheong","label":"대청","x0":0,"x1":320,"wallpaperUrl":"/shrine/stage/naru/room-wall-mural.webp","flooringUrl":"/shrine/stage/naru/room-floor-mural.webp","structures":[{"code":"platform-naru","assetUrl":"/shrine/stage/banga/platform.webp","x":50,"y":51,"w":44,"anchors":[]},{"code":"altar-naru","assetUrl":"/shrine/stage/banga/altar-top.webp","x":50,"y":58,"w":58,"anchors":[{"id":"altar-left","layer":"altar","x":45,"y":53.5,"label":"제단 왼편"},{"id":"altar-center","layer":"altar","x":50,"y":53.5,"label":"제단 가운데"},{"id":"altar-right","layer":"altar","x":55,"y":53.5,"label":"제단 오른편"}]}]}]}'::jsonb
where code = 'naru' and (stage -> 'zones') is null;

-- 확인 쿼리
--   SELECT code,
--          stage->>'width'                                     AS width,
--          jsonb_array_length(stage->'zones')                  AS zones,
--          stage->'zones'->0->>'wallpaperUrl'                  AS room_wall,
--          jsonb_array_length(stage->'zones'->0->'structures') AS zone_structures,
--          stage->'light'->>'color'                            AS light
--     FROM public.shrine_theme_packs ORDER BY sort_order;
